services:
  mongodb:
    image: mongo:latest
    ports:
      - "27017:27017"
    volumes:
      - mongodb_data:/data/db
    environment:
      MONGO_INITDB_ROOT_USERNAME: mongo-shared-dev
      MONGO_INITDB_ROOT_PASSWORD: fikTpih4U2!
  backend:
    build:
      context: ./backend
    ports:
      - "3000:3000"
    depends_on:
      - mongodb
    environment:
      # DB_URI: mongodb://mongo-shared-dev:fikTpih4U2!@mongo:27017/?authMechanism=DEFAULT
      DB_URI: mongodb://mongo-shared-dev:fikTpih4U2!@mongodb:27017/?authSource=admin
  frontend:
    build: ./frontend
    ports:
      - "4000:80"
    depends_on:
      - backend
volumes:
  mongodb_data: